# NSA.cpp

all: Exercise1

# This compilation command forces the compiler to use the C++ 11 standard.
# -Wall flag shows all warnings (not just errros)
Exercise1: NSA.cpp secrets.h
    g++ NSA.cpp -o NSA -std=c++11 -Wall

clean:
    rm *.0 NSA